### ISSUE TITLE
ssh functionality

### ISSUE THREAD

**Issue by DeathWired** [cppshane/Background-Terminal#4]
when i use ssh it says its not a recognized command, is there a way to fix this?

**Comment by cppshane** [comment]
SSH works fine for me. The program just uses cmd.exe, so try using the SSH command in a standard CMD terminal and see if it also gives the error. If so, it's just a problem with your Windows.

**Comment by DeathWired** [comment]
I have used ssh in a regular terminal, i can take a video of using ssh in cmd and trying it on yours

**Comment by cppshane** [comment]
Then the program must be accessing an incorrect version of cmd.exe. I know SSH functionality was only recently implemented, and there can be several versions of cmd.exe located in different places in Windows, so my guess is that your path is attempting to access a version of one that doesn't have the new ssh functionality.

I was planning on implementing a few new settings, one of which is to implement specific paths for IO to programs. I'll push it out later this week, and you should be able to manually set the exact path of the cmd.exe that properly supports ssh.

**Comment by DeathWired** [comment]
That sounds great thank you!

**Comment by DeathWired** [comment]
I figured out what i think my problem was, i didnt install the sdk .net version and i used the 32 bit version, but its great to hear your still working on this

**Comment by DeathWired** [comment]
![ssh](https://user-images.githubusercontent.com/37221707/87238120-77455a80-c3cc-11ea-83d2-ca6f59f292be.PNG)
turns out i was wrong says its a fake terminal and doesnt allow ssh, you might need to implement it for ssh, otherwise im not sure why its happening

**Comment by cppshane** [comment]
Implemented changes in commit 2692f72d8d924f89feae27f6dc75d7ef9c7e6e4f.

v1.2.0 released, and it allows for user inputted process path.

**Comment by cppshane** [comment]
It looks like even with user input this can still occur. Running it with "-tt" option fixes this, however it doesn't seem to ask the user for login credentials upon ssh attempt. Will look into this.

**Comment by cppshane** [comment]
Yeah so it looks like I'll need to manually implement ssh handling, since apparently while you can send a singular ssh command with stdin, you can't open an active session (which actually makes sense). I'll push this functionality out in the next commit.

**Comment by DeathWired** [comment]
I got that error as well, thank you for putting so much time into this, I appreciate it

**Comment by cppshane** [comment]
Alright, just implemented SSH and released in v1.2.1.
